// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dormitory.domain;

import com.dormitory.domain.Roomtype;

privileged aspect Roomtype_Roo_JavaBean {
    
    public String Roomtype.getType() {
        return this.type;
    }
    
    public void Roomtype.setType(String type) {
        this.type = type;
    }
    
}
