// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.dormitory.domain;

import com.dormitory.domain.Trainer;

privileged aspect Trainer_Roo_JavaBean {
    
    public String Trainer.getName() {
        return this.name;
    }
    
    public void Trainer.setName(String name) {
        this.name = name;
    }
    
}
